name : my first workflow

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: check and read files
          run: |
           echo "My first job"
           ls
           cat README.md

        - name: generate ASCII network
          run: cowsay -f dragon "run for cover . I am a dragon" >> dragon.txt 